import type { Metadata } from "next";
import { Geist, Geist_Mono, Titillium_Web, Lexend_Deca } from "next/font/google";
import "./globals.css";
import Navigate from "@/components/Navigate/Navigate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexendDeca = Lexend_Deca({
    subsets: ["latin"],
    weight: ["200", "300", "400", "600", "700"], // tùy bạn chọn
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='mdl-js'>
      <body
        className={`${lexendDeca.className} antialiased`}
      >
      <Navigate/>
        {children}
      </body>
    </html>
  );
}
